### ISSUE TITLE
Unclear use of 'maxProfit'

### ISSUE THREAD

**Issue by LittleLionMan** [White-Whale-Defi-Platform/migaloo-bots#11]
https://github.com/White-Whale-Defi-Platform/migaloo-bots/blob/98ac905a6fbb36df88e5f2976164e99abecbe870/src/arbitrage/optimizers/analyticalOptimizer.ts#L120-L134

Sorry, I have no clue about Typescript and this is most likely not helpful, but what's up with 'maxProfit' in line 127. Isn't it always 0?

**Comment by NotJeremyLiu** [comment]
@LittleLionMan the value of maxProfit changes in line 128 based on if the profit from a given path is greater than the current maxProfit. maxProfit just starts out at 0.

**Comment by LittleLionMan** [comment]
I'm so stupid. It's a a map method. Well at least I know how to create an issue, now.

**Comment by SirTLB** [comment]
@LittleLionMan thanks for the issue and don't feel stupid. We love people to hang out here and create issues if unclear. The method should contain comments in code and if not, we should add them. The code is definitely missing comments on a lot of places.
@NotJeremyLiu thanks for answering!
