### ISSUE TITLE
Adding pools with CW20-tokens errors

### ISSUE THREAD

**Issue by LittleLionMan** [White-Whale-Defi-Platform/migaloo-bots#14]
Tried to add the Posthuman - Juno pool and got this output:
Error: Query failed with (18): Error parsing into type cw20_base_mintable::msg::QueryMsg: unknown variant `info`, expected one of `balance`, `token_info`, `minter`, `allowance`, `all_allowances`, `all_accounts`, `marketing_info`, `download_logo`: query wasm contract failed: invalid request
    at QueryClient.queryUnverified (.../node_modules/@cosmjs/stargate/build/queryclient/queryclient.js:107:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.queryContractSmart (.../node_modules/@cosmjs/cosmwasm-stargate/build/modules/wasm/queries.js:59:34)
    at async initPools (.../out/juno/queries/getPoolState.js:42:25)
    at async main (.../out/index.js:82:19)

**Comment by kaimen-sano** [comment]
Can you link the two cw20 assets in the pool?

**Comment by SirTLB** [comment]
This don't seem like a "pool" contract to me, can you comment with the address or the POOL variable from the config? (As @kaimen-sano suggests)

**Comment by LittleLionMan** [comment]
Yes, you guys are right. It was the token address. Interestingly I messed this up on two different occasions for one or more pools. Is there a better possibility to look up Pool addresses than directly in the repo https://github.com/CosmosContracts/junoswap-asset-list/blob/main/pools_list.json?

**Comment by SirTLB** [comment]
unfortunately not for junoswap no. For most other dexes like Astroport, White Whale you can query the "Factory" with the message {"pairs":{}} and it will return all pairs created by that factory, those are usually the pairs listed by that dex.
