### ISSUE TITLE
Add more config examples (e.g. Terra)

### ISSUE THREAD

**Issue by josh-burton** [White-Whale-Defi-Platform/migaloo-bots#8]
This would be really helpful.

**Comment by SirTLB** [comment]
Good one, we actually had a few but deleted in recent commit. 
meanwhile you can check out: 
* https://ww0-1.gitbook.io/migaloo-docs/client-documentation/arbitrage_botsv
* https://ww0-1.gitbook.io/migaloo-docs/client-documentation/arbitrage_bots/configexample

they hold an example for juno
